services:
  sistema-llamadas:
    image: ubuntu:24.04
    container_name: sistema-llamadasv2
    volumes:
      - ../nginx:/etc/nginx/sites-available
      - ../mariaDB:/mariaDB
      - ../scripts:/scripts
      - ../program:/program
    ports:
      - "8080:80"
    command: bash -c "chmod +x /scripts/* && /scripts/start-services.sh"

